config/routes.rb
Rails.application.routes.draw do
  get '/likes/gossip/:id', to: 'likes#like_gossip'
  get '/dislikes/gossip/:id', to: 'likes#dislike_gossip'
  # get "/gossips/comment_modal" => 'comments#new_comment', :as => :new_comment
  # get '/likes/like_comment/:id', to: 'likes#like_comment'
  #root url
  get '/', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'

  #login
  get '/login', to: 'login#login'
  post '/login', to: 'login#login_check'
  get '/logout', to: 'login#logout'

  #profil
  get '/profil', to: 'profil#index'
  resources :gossips, :users, :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :gossip, optional: true
  belongs_to :comment, class_name: "Comment", optional: true
	has_many :comments, class_name: "Comment"
end

app/models/gossip.rb
class Gossip < ActiveRecord::Base
	belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  # has_many :comments
  has_many :likes 
end

app/models/like.rb
class Like <  ActiveRecord::Base
	belongs_to :user
	# belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/tag.rb
class Tag <  ActiveRecord::Base
	has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ActiveRecord::Base
	# has_many :comments
	has_many :likes
	has_many :gossip
	has_and_belongs_to_many :users

	def has_liked_gossip(gossip_id)
		Like.where(user_id: self.id, gossip_id: gossip_id).empty?
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :json

  def new
    @comment = Comment.new
    respond_modal_with @comment
  end

  def create
    puts params['gossip_id']
    @comment = Comment.create(content: params[:comment][:content], gossip_id: params['gossip_id'], user_id: params['user_id'])
    @comment.save
    redirect_to "/gossips/#{params['gossip_id']}"
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  protect_from_forgery prepend: true
  before_action :set_gossip, only: [:update, :edit, :show, :destroy]
  def index
  	@gossips = Gossip.all
  end


  def new
    @gossip = Gossip.new
  end

  def show
    @comment = Comment.new
    @comments = Comment.where(gossip_id: @gossip.id)
  end

  def create
    @gossip = Gossip.new
    @gossip.content = params[:gossip][:content]
    @gossip.title = params[:gossip][:title]
    if params['user_id']
      @gossip.user_id = params['user_id']
    else
      @gossip.anonymous_gossiper = params[:gossip][:anonymous_gossiper] 
    end
    @gossip.save

    redirect_to "/gossips"
  end

  def update
    @gossip.content = params[:gossip][:content]
    @gossip.save

    redirect_to "/gossips/#{@gossip.id}"
  end
  def destroy
    if @user != "nil" || @user != "Nil"
      if @user.id == @gossip.user_id
        @gossip.delete
        redirect_to "/gossips"
      # else
        # Errors
      end
    end
  end

  def set_gossip
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like_gossip
  	like = Like.new(user_id: session['id'], gossip_id: params['id'])
  	like.save
  end

  def dislike_gossip
  	like = Like.find_by(user_id: session['id'], gossip_id: params['id'])
  	like.delete
  end

  def like_comment
  	like = Like.new(comment_id: params['id'], user_id: session['id'])
  	like.save
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	protect_from_forgery prepend: true
	skip_before_action :verify_authenticity_token

	def login
		render 'login/login.html.erb'
	end

  def login_check
    @user = User.find_by(email: params[:email])
    # puts @user.class
    if @user != "nil" || @user != "Nil"
  		if @user.password == params[:password]
        session[:id] = @user.id
        redirect_to '/profil'
      end
    else  
      redirect_to '/'
      # puts "mabite"
    end
  end

  def logout
  	reset_session
  	redirect_to '/'
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def index
  	likes = User.all
  	# puts likes.size
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	protect_from_forgery prepend: true
  skip_before_action :verify_authenticity_token
	before_action :set_user, only: [:update, :edit, :show, :destroy]

	def index
		@users = User.all
		render 'users/index'
	end

  def new
  	render 'users/new'
  end

  def create
  	@user = User.new(username: params[:username], email: params[:email], bio: params[:bio], password: params[:password])
  	@user.save
  	redirect_to "/login"
  end

  def show
  end

  def edit
  end

  def set_user
  	@user = User.find(params[:id])
  end

  def destroy
    @user.delete
    redirect_to "/users"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenue_helper.rb
module BienvenueHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/index.html.erb
<h1>Messages</h1>

<div class="card-columns">
  <%= render @messages %>
</div>

app/views/comments/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">New comment</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', comment: @comment %>

app/views/gossips/delete.html.erb
<h1>Gossip#delete</h1>
<p>Find me in app/views/gossip/delete.html.erb</p>

app/views/gossips/edit.html.erb
<style>
  .flex-outer li {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  .flex-outer > li > label, .flex-outer li p {
    flex: 1 0 120px;
    max-width: 220px;
    }

  .flex-outer > li > label + * {
    flex: 1 0 220px;
  }

  .flex-outer li button {
    margin-left: auto;
    padding: 8px 16px;
    border: none;
    background: #333;
    color: #f2f2f2;
    text-transform: uppercase;
    letter-spacing: .09em;
    border-radius: 2px;
  }
</style>

<div >
  <h1>Editer mon ragot</h1>

  <%= form_for @gossip do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
  <% end %>


</div>

app/views/gossips/index.html.erb
<%= stylesheet_link_tag 'gossip', media: 'all' %>

<div class="gossips">
	<h1> Découvrez tous les gossips ! </h1>
<br>
	<% @gossips.each do |gossip| %>
		<div class="gossip">
				<p>
					<% if gossip.user_id.nil? %>
						Author : <%= gossip.anonymous_gossiper.capitalize %>
					<% else %>
						Author : <%= User.find(gossip.user_id).username.capitalize %>
					<% end %>
				</p>
				<p>
					Title : 
					<%= gossip.title.capitalize %>
					<br>
					<ul class="buttons">
						<li>
							<%= link_to "Details", gossip_path(gossip), :class=>"btn btn-primary" %>
						</li>
						<% if !@user.nil? %>
							<% if @user.id == gossip.user_id %>
								<li>
									<%= link_to "Delete", gossip_path(gossip), method: :delete, :class=>"btn btn-primary" %>
								</li>
							<% end %>

						<li>
						</li>
						<li>
							<% if !@user.has_liked_gossip(gossip.id) %>
								<span>
									<a href="/dislikes/gossip/<%= gossip.id %>" data-remote=true class="em em-heart"></a>
								</span>
							<% else %>
								<a href="/likes/gossip/<%= gossip.id %>" data-remote=true class="btn btn-primary">Like !</a>
							<% end %>
						</li>
					<% end %>
					</ul>
				</p>
			</div>
	<% end %>
</div>

app/views/gossips/new.html.erb
<div>
  <h1>Tell us your last gossip !</h1>
  <%= form_for @gossip, :url => gossips_path do |f| %>
    <% if @user %>
      <%= hidden_field_tag :user_id, @user.id %>
    <% else %>
      <div class="field">
        <%= f.label :anonymous_gossiper %><br>
        <%= f.text_field :anonymous_gossiper %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/gossips/show.html.erb
<%= stylesheet_link_tag 'gossip', media: 'all' %>

<div>
	<div id="gossip">
		<div class="actions">
			<ul>
				<li>
					<% if !@user.nil? && @user.id == @gossip.user_id %>
						<%= link_to "Supprimer mon ragot", gossip_path(@gossip), method: :delete, :class => "btn btn-primary" %>
						<%= link_to "Editer mon ragot", edit_gossip_path(@gossip), method: :get, :class =>"btn btn-primary" %>
					<% end %>
				</li>
			</ul>
		</div>
		<table class="table table-condensed">
			<tr>
				<th>Author</th>
				<td>
					<% if @gossip.user_id.nil? %>
						<%= gossip.anonymous_gossiper %>
					<% else %>
						<%= User.find(@gossip.user_id).username %>
					<% end %>
				</td>
			</tr>

			<tr>
				<th>Title</th>
				<td>
					<%= @gossip.title.capitalize %>
				</td>
			</tr>

			<tr>
				<th>Content</th>
				<td>
					<%= @gossip.content %>
				</td>
			</tr>
		</table>
	</div>

	<div id="gossip-show" class="comments">
			<table>
					<% @comments.each do |comment| %>
					<tr>
						<th><%= User.find(comment.user_id).username %> a dit :</th>
						<td><%= comment.content %></td>
					</tr>
					<% end %>
		</table>
	</div>
<br><br>
	<div id="show_form">
		<%= form_for @comment, :url => comments_path do |f| %>
	      <%= hidden_field_tag :gossip_id, @gossip.id %>
	      <% if @user %>
	    		<%= hidden_field_tag :user_id, @user.id %>
	 			<% end %>
	      <div class="field">
	        <%= f.text_field :content %>
	      </div>
	    <div class="actions">
	      <%= f.submit class: "btn btn-primary" %>
	    </div>
	  <% end %>
	</div>
</div>

app/views/likes/like_comment.html.erb
<h1>Likes#like_comment</h1>
<p>Find me in app/views/likes/like_comment.html.erb</p>

app/views/likes/like_gossip.html.erb
<h1>Likes#like_gossip</h1>
<p>Find me in app/views/likes/like_gossip.html.erb</p>

app/views/user/index.html.erb
<style>
  .flex-outer li {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  .flex-outer > li > label, .flex-outer li p {
    flex: 1 0 120px;
    max-width: 220px;
  }

</style>
<div>
	<h1> Tous les utilisateurs</h1>
	<h3><a href="/users/new">Créer un utilisateur</a></h3>
	<div>
		<ul class=".flex-outer">
			<% @users.each do |user| %>
				<li> <%= user.username %> </li>
			<% end %>
		</ul>
	</div>
</div>

app/views/user/new.html.erb
<style>
  .flex-outer li {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  .flex-outer > li > label, .flex-outer li p {
    flex: 1 0 120px;
    max-width: 220px;
    }

  .flex-outer > li > label + * {
    flex: 1 0 220px;
  }

  .flex-outer li button {
    margin-left: auto;
    padding: 8px 16px;
    border: none;
    background: #333;
    color: #f2f2f2;
    text-transform: uppercase;
    letter-spacing: .09em;
    border-radius: 2px;
  }
</style>
<div >
  <h1>Créer un utilisateur</h1>
  <form action="/users/create" method="post">
    <ul class="flex-outer">
      <li>
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter your username here"/>
      </li>
      <li>
        <label for="email">Email</label>
        <input type="email" name="email" placeholder="Enter your email here" />
      </li>
      <li>
        <label for="bio">Bio</label>
        <input type="text" name="bio" placeholder="Enter your bio here"/>
      </li>
      <li>
        <button type="submit" value="Create user"></button>
      </li>
    </ul>
  </form>
</div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/index.html.erb
<style>
  .flex-outer li {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  .flex-outer > li > label, .flex-outer li p {
    flex: 1 0 120px;
    max-width: 220px;
  }

</style>
<div>
	<h1> Tous les utilisateurs</h1>
	<h3><a href="/users/new">Créer un utilisateur</a></h3>
	<div>
		<ul class=".flex-outer">
			<% @users.each do |user| %>
				<li> <%= user.username %> </li>
				<li> <%= link_to "Delete", user_path(user), method: :delete %> </li>
			<% end %>
		</ul>
	</div>
</div>

app/views/users/new.html.erb
<style>
  .flex-outer li {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  .flex-outer > li > label, .flex-outer li p {
    flex: 1 0 120px;
    max-width: 220px;
    }

  .flex-outer > li > label + * {
    flex: 1 0 220px;
  }

  .flex-outer li button {
    margin-left: auto;
    padding: 8px 16px;
    border: none;
    background: #333;
    color: #f2f2f2;
    text-transform: uppercase;
    letter-spacing: .09em;
    border-radius: 2px;
  }
</style>

<div >
  <h1>Sign up </h1>
  <form action="/users" method="post">
    <ul class="flex-outer">
      <li>
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter your username here"/>
      </li>
      <li>
        <label for="email">Email</label>
        <input type="email" name="email" placeholder="Enter your email here" />
      </li>

      <li>
        <label for="email">Password</label>
        <input type="password" name="password" placeholder="Enter your password here" />
      </li>

      <li>
        <label for="bio">Bio</label>
        <input type="text" name="bio" placeholder="Enter your bio here"/>
      </li>
      <li>
        <button type="submit" value="Create user"></button>
      </li>
    </ul>
  </form>
</div>

app/views/users/show.html.erb
test